# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Data Science Course Blog
tagline:          'Data Science for an Expanding Universe'
description:      'Featuring work, thoughts and discussions from GA DAT 9'
url:              datadave.github.io/courseblog/
baseurl: /courseblog

author:
  name:           'Dave Goodsmith'
  url:            https://twitter.com/thegoodsmith


paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/datadave/courseblog
