# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Course Journal
tagline:          'Data Science for an Expanding Universe'
description:      'A home for musings and showcases for the exposition of datonic mastifications'
url:              http://lanyon.getpoole.com
baseurl: /courseblog

author:
  name:           'Dave Goodsmith'
  url:            https://twitter.com/thegoodsmith


paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/datadave/courseblog
